---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Ensure partition does not exist
    zhmc_partition:
      hmc: "{{ hmc }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition_name }}"
      state: absent
